name: Update Kablo TV
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Her gün 03:00'te (UTC)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run API Script
        run: python kablo_api.py

      - name: Commit M3U
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kablo_tv.m3u
          git diff-index --quiet HEAD || git commit -m "Auto-update [$(date +'%d.%m.%Y')]"
          git push

      - name: Upload Errors
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: error.log
